export default {
  HotPlayData:[],//当季玩大数据
  HotPlayList:{},//当季玩数据
  characteristicRecommendList:[],//特色推荐数据
  themeTypeList:[],//酒店搜索详情酒店主题搜索
  roomHardList:[],//酒店搜索详情房间设施搜索
  searchData:[],//酒店搜索详情数据
  hotDestinationList:[],//当季热门数据
  hotelDetalis:{},//酒店详情
  hotelModel:{},//酒店详情基本信息
  hotelPolicy:{},//酒店政策
  hotelImage:[],//酒店图片
  exteriorList:[],//酒店图片外观
  theLobbyList:[],//酒店图片大堂
  restaurantList:[],//酒店图片餐厅
  publicAreasList:[],//公共区域
  hotelIconList:[],//图标
  hardServiceObj:{},//酒店设施服务基本信息
  introduceList:[],//推荐类型

  searchHotelRoomFilterObj:{},//房间搜索条件
  hotelRoom:[],//酒店房间列表
  hotelOrderDetail:{},//酒店订单详情
  qLCityData:[],//青旅酒店南京
  szCityData:[],//青旅酒店苏州
  xMCityData:[],//青旅酒店厦门
  bGCityData:[],//青旅酒店北京
  cDCityData:[],//青旅酒店成都
  wZCityHotelData:[],//乌镇
  jZCityHotelData:[],//周庄
  cHCityHotelData:[],//吃货
  yXCityHotelData:[],//阳朔
  wHTCityHotelData:[],//玩海滩
  yLYCityHotelData:[],//游乐园
  tLSCityHotelData:[],//探历史
  cMSCityHotelData:[],//尝美食
  aHHSCityHotelData:[],//安徽黄山
  tATSCityHotelData:[],//泰安泰山
  qDLSCityHotelData:[],//青岛崂山
  zJSCityHotelData:[],//南京紫金山
  dQXGCityHotelData:[],//迪庆香格里拉
  sYFHLCityHotelData:[],//三亚凤凰岭
  wLFCityHotelData:[],//厦门五老峰
  pTSCityHotelData:[],//舟山普陀山
  lJKZCityHotelData:[],//丽江客栈
  dLKZCityHotelData:[],//大理客栈
  xMKZCityHotelData:[],//厦门客栈
  hZKZCityHotelData:[],//杭州客栈
  sYKZCityHotelData:[],//三亚客栈
  zTJDCityHotelData:[],//主题酒店
  yCTYCityHotelData:[],//圆床体验
  mXTYCityHotelData:[],//冒险体验
  gDXCCityHotelData:[],//高档享受

}
